# Generated by Django 4.0.1 on 2022-02-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Currency Name')),
                ('value', models.FloatField(max_length=100, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_created', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['-created'],
            },
        ),
    ]
